### ISSUE TITLE
Out of memory exception

### ISSUE THREAD

**Issue by shashank090789** [iDevicesInc/SweetBlue#132]
I got this  error first time, following is the stack trace

java.lang.OutOfMemoryError
       at com.idevicesinc.sweetblue.BleDevice$ConnectionFailListener$ConnectionFailEvent.<init>(BleDevice.java:1107)
       at com.idevicesinc.sweetblue.P_ConnectionFailManager.onConnectionFailed(P_ConnectionFailManager.java:104)
       at com.idevicesinc.sweetblue.BleDevice.onNativeConnectFail(BleDevice.java:3388)
       at com.idevicesinc.sweetblue.P_BleDevice_Listeners$1.onStateChange_synchronized(P_BleDevice_Listeners.java:68)
       at com.idevicesinc.sweetblue.P_BleDevice_Listeners$1.onStateChange(P_BleDevice_Listeners.java:45)
       at com.idevicesinc.sweetblue.PA_Task.setState(PA_Task.java:154)
       at com.idevicesinc.sweetblue.PA_Task.setEndingState(PA_Task.java:290)
       at com.idevicesinc.sweetblue.P_TaskQueue.endCurrentTask(P_TaskQueue.java:242)
       at com.idevicesinc.sweetblue.P_TaskQueue.access$600(P_TaskQueue.java:8)
       at com.idevicesinc.sweetblue.P_TaskQueue$3.run(P_TaskQueue.java:308)
       at com.idevicesinc.sweetblue.utils.UpdateLoop.postIfNeeded(UpdateLoop.java:156)
       at com.idevicesinc.sweetblue.P_TaskQueue.tryEndingTask(P_TaskQueue.java:300)
       at com.idevicesinc.sweetblue.PA_Task.fail(PA_Task.java:205)
       at com.idevicesinc.sweetblue.P_Task_Connect.onNativeFail(P_Task_Connect.java:108)
       at com.idevicesinc.sweetblue.P_BleDevice_Listeners.onNativeConnectFail(P_BleDevice_Listeners.java:304)
       at com.idevicesinc.sweetblue.P_BleDevice_Listeners.onConnectionStateChange_synchronized(P_BleDevice_Listeners.java:267)
       at com.idevicesinc.sweetblue.P_BleDevice_Listeners.access$100(P_BleDevice_Listeners.java:20)
       at com.idevicesinc.sweetblue.P_BleDevice_Listeners$2.run_nested(P_BleDevice_Listeners.java:148)
       at com.idevicesinc.sweetblue.P_BleDevice_Listeners$SynchronizedRunnable.run(P_BleDevice_Listeners.java:32)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5602)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by dougkoellmer** [comment]
Unless this happens consistently and reproducibly, this happened simply because your app hit memory limits and "the straw on the camel's back" was a normal ~20 byte heap allocation inside SweetBlue. In other words I don't believe this is a bug in SweetBlue.

You may be allocating/leaking too much memory elsewhere in your app. Most of the time this happens when working with large images.
